// Deterministic evidence reasoning.
//
// Turns structured analysis (PostgreSQL) + recalled memory (Hindsight) +
// previous structured cases into FACTS, INFERENCES and UNKNOWNS.
// Every number below is computed by code; nothing is generated by an LLM.

const dates = require('../../lib/dates');
const { inr, pct, round } = require('../../lib/num');

const key = {
  session: (id) => `session:${id}`,
  baseline: (seg) => `baseline:${seg}`,
  comparable: (id) => `comparable:${id}`,
  event: (id) => `platform_event:${id}`,
  memory: (id) => `memory:${id}`,
  investigation: (id) => `investigation:${id}`
};

const incentiveTerms = /incentive|bonus|eligib/i;

/** Evidence catalogue for an analysis (used by agent answers and investigations). */
const buildEvidence = ({ analysis, memory, previousCases }) => {
  const { current, baseline, comparables, platformEvents } = analysis;
  const items = [
    {
      id: key.session(current.sessionId),
      type: 'EARNINGS_RECORD',
      label: `Earnings record · ${dates.pretty(current.date)} ${current.window}`,
      detail: `${current.orders} orders · net ${inr(current.net)} (base ${inr(current.basePay)}, incentive ${inr(current.incentive)}, tips ${inr(current.tips)}, deductions ${inr(current.deductions)}) · acceptance ${current.acceptanceRate}%`,
      localDate: current.date,
      source: 'PostgreSQL · earnings_records / work_sessions',
      refId: current.sessionId
    },
    {
      id: key.baseline(current.segmentKey),
      type: 'BASELINE',
      label: `Personal baseline · ${baseline.label}`,
      detail: `${baseline.sampleSize} sessions (${baseline.windowStart ? dates.short(baseline.windowStart) : '—'} – ${baseline.windowEnd ? dates.short(baseline.windowEnd) : '—'}) · median net ${inr(baseline.net.median)} · range ${inr(baseline.net.min)}–${inr(baseline.net.max)} · orders ${baseline.orders.min}–${baseline.orders.max}`,
      localDate: baseline.windowEnd,
      source: 'Computed by analytics engine',
      refId: current.segmentKey
    },
    ...comparables.map((c) => ({
      id: key.comparable(c.sessionId),
      type: 'COMPARABLE_SESSIONS',
      label: `Comparable shift · ${dates.pretty(c.date)} ${c.window}`,
      detail: `${c.orders} orders · net ${inr(c.net)} · incentive ${inr(c.incentive)} · similarity ${c.similarity} (${c.reasons.join(', ')})`,
      localDate: c.date,
      source: 'Comparable session engine',
      refId: c.sessionId
    })),
    ...platformEvents.map((e) => ({
      id: key.event(e.id),
      type: 'PLATFORM_EVENT',
      label: `Platform event · ${dates.pretty(e.localDate)} · ${e.title}`,
      detail: e.description,
      localDate: e.localDate,
      source: e.source,
      refId: e.id
    })),
    ...(memory?.memories || []).map((m) => ({
      id: key.memory(m.id),
      type: 'HINDSIGHT_MEMORY',
      label: `Hindsight memory${m.category ? ` · ${m.category.replace(/_/g, ' ')}` : ''}`,
      detail: m.text,
      localDate: m.localDate,
      source: 'Hindsight recall',
      refId: m.id
    })),
    ...(previousCases || []).map((c) => ({
      id: key.investigation(c.id),
      type: 'PREVIOUS_INVESTIGATION',
      label: `Previous case ${c.caseNumber} · ${dates.pretty(c.periodStart)}`,
      detail: `${c.title}. Outcome: ${c.result || 'not yet resolved'}`,
      localDate: c.resolvedLocalDate || c.periodStart,
      source: 'PostgreSQL · investigations / investigation_outcomes',
      refId: c.id
    }))
  ];
  return items;
};

/** Structured previous case referenced by a recalled memory (via metadata), if any. */
const linkedCase = (m, previousCases) => {
  const id = m.metadata?.investigationId;
  return id ? previousCases.find((c) => c.id === id) : null;
};

/**
 * Core reasoning over one session.
 * @returns {{summary, facts, inferences, unknowns, historicalContext, recommendedActions, recommendedQuestions, timeline, primaryFactor}}
 */
const reasonAboutSession = ({ analysis, memory, previousCases = [], worker, useMemory = true, useHistory = true }) => {
  const { current, baseline, comparables, comparableSummary, evaluation, platformEvents } = analysis;
  const facts = [];
  const inferences = [];
  const unknowns = [];
  const actions = [];
  const questions = [];
  const historicalContext = [];
  const dateLabel = dates.pretty(current.date);
  const shift = `${current.dayName} ${current.window} · ${current.zone}`;

  // ── FACTS ──────────────────────────────────────────────────────────────────
  facts.push({
    text: `On ${dateLabel} (${shift}) you completed ${current.orders} orders and earned ${inr(current.net)} net (base pay ${inr(current.basePay)}, incentive ${inr(current.incentive)}, tips ${inr(current.tips)}, deductions ${inr(current.deductions)}).`,
    evidence: [key.session(current.sessionId)]
  });

  if (!useHistory) {
    unknowns.push({ text: 'Without your history it is not possible to tell whether these earnings are unusual for you.' });
    return finalize({ current, facts, inferences, unknowns, historicalContext, actions, questions, evaluation: null, summary: `On ${dateLabel} you earned ${inr(current.net)} from ${current.orders} orders. I can only see this one shift, so I cannot say whether that is normal for you.` });
  }

  const enoughHistory = baseline.sampleSize >= 3;
  if (!enoughHistory) {
    unknowns.push({ text: `Only ${baseline.sampleSize} comparable earlier sessions exist, so a reliable personal baseline cannot be computed yet.` });
  } else {
    const dev = evaluation.deviationPct;
    facts.push({
      text: `Your personal baseline for ${baseline.label} is ${inr(baseline.net.median)} (median of ${baseline.sampleSize} sessions from ${dates.short(baseline.windowStart)} to ${dates.short(baseline.windowEnd)}; range ${inr(baseline.net.min)}–${inr(baseline.net.max)}). This shift was ${pct(dev)} ${dev < 0 ? 'below' : 'above'} it.`,
      evidence: [key.baseline(current.segmentKey), key.session(current.sessionId)]
    });
    const ordersNormal = current.orders >= baseline.orders.min - 1 && current.orders <= baseline.orders.max + 1;
    facts.push({
      text: ordersNormal
        ? `Order volume was normal: ${current.orders} completed orders against your usual ${baseline.orders.min}–${baseline.orders.max} for this shift.`
        : `Order volume was outside your usual range: ${current.orders} completed orders against ${baseline.orders.min}–${baseline.orders.max}.`,
      evidence: [key.session(current.sessionId), key.baseline(current.segmentKey)]
    });
  }

  if (comparableSummary) {
    facts.push({
      text: `I found ${comparableSummary.count} comparable shifts (same day, window and zone with similar order volume). They averaged ${inr(comparableSummary.avgNet)} net with ${round(comparableSummary.avgOrders, 1)} orders and ${inr(comparableSummary.avgIncentive)} incentive; this shift was ${inr(Math.abs(comparableSummary.netGap))} ${comparableSummary.netGap < 0 ? 'lower' : 'higher'}.`,
      evidence: comparables.map((c) => key.comparable(c.sessionId))
    });
  }

  const incentiveSignal = evaluation?.signals?.find((s) => s.key === 'incentive');
  const incentiveDropped = incentiveSignal?.status === 'dropped';
  if (current.incentiveProgram) {
    const paidOn = comparables.filter((c) => c.incentive > 0).length;
    facts.push({
      text: `${current.incentiveProgram}: ${inr(current.incentive)} on this shift${current.incentiveNote ? ` (platform note: "${current.incentiveNote}")` : ''}.${comparables.length ? ` It was paid on ${paidOn} of ${comparables.length} comparable shifts.` : ''}`,
      evidence: [key.session(current.sessionId), ...comparables.map((c) => key.comparable(c.sessionId))]
    });
  }

  const dec = evaluation?.decomposition;
  if (enoughHistory && dec && dec.totalDelta < 0) {
    const parts = dec.parts.filter((p) => Math.abs(p.amount) >= 5).sort((a, b) => a.amount - b.amount);
    facts.push({
      text: `Compared with the baseline average (${inr(baseline.net.mean)}), net earnings were ${inr(Math.abs(dec.totalDelta))} lower. Breakdown: ${parts.map((p) => `${p.label.toLowerCase()} ${p.amount < 0 ? '−' : '+'}${inr(Math.abs(p.amount)).replace('₹', '₹')}`).join(', ')}.`,
      evidence: [key.baseline(current.segmentKey), key.session(current.sessionId)]
    });
  }

  facts.push({
    text: `Acceptance rate was ${current.acceptanceRate}%${enoughHistory ? ` (your usual: ${baseline.acceptanceRate.median}%)` : ''}; deductions were ${inr(current.deductions)}${enoughHistory ? ` (usual ${inr(baseline.deductions.median)})` : ''}; idle time ${current.idleHours}h.`,
    evidence: [key.session(current.sessionId)]
  });

  const otherZones = Object.entries(current.zoneBreakdown || {}).filter(([z]) => z !== current.zone);
  const otherZoneOrders = otherZones.reduce((a, [, n]) => a + n, 0);
  if (otherZoneOrders > 0) {
    facts.push({
      text: `${otherZoneOrders} of ${current.orders} orders (${pct((otherZoneOrders / current.orders) * 100)}) were delivered outside your home zone (${otherZones.map(([z, n]) => `${z}: ${n}`).join(', ')}).`,
      evidence: [key.session(current.sessionId)]
    });
  }

  for (const e of platformEvents) {
    facts.push({ text: `On ${dates.pretty(e.localDate)} the platform recorded: "${e.title}".`, evidence: [key.event(e.id)] });
  }

  // ── INFERENCES ─────────────────────────────────────────────────────────────
  const primary = dec?.primaryFactor;
  if (enoughHistory && evaluation.deviationPct < -10) {
    if (primary === 'incentive') {
      const share = Math.abs(dec.parts.find((p) => p.key === 'incentive').amount / dec.totalDelta) * 100;
      inferences.push({
        text: `The drop is mainly explained by the missing ${current.incentiveProgram || 'incentive'} rather than lower demand: order volume and pay per order were normal, and the incentive accounts for about ${pct(Math.min(share, 100))} of the gap.`,
        confidence: share >= 70 ? 'HIGH' : 'MEDIUM',
        basis: 'Deterministic breakdown of the change against your personal baseline'
      });
    } else if (primary === 'order_volume') {
      inferences.push({
        text: 'The drop is mainly explained by fewer completed orders than usual, not by a change in pay rates or incentives.',
        confidence: 'HIGH',
        basis: 'Deterministic breakdown of the change against your personal baseline'
      });
    } else if (primary === 'pay_per_order') {
      inferences.push({ text: 'The drop is mainly explained by lower base pay per order.', confidence: 'MEDIUM', basis: 'Breakdown against baseline' });
    } else if (primary === 'deductions') {
      inferences.push({ text: 'The drop is mainly explained by higher deductions.', confidence: 'MEDIUM', basis: 'Breakdown against baseline' });
    }
  }

  const incentiveEvents = platformEvents.filter((e) => e.type === 'INCENTIVE_TERMS_CHANGE');
  const zoneEvents = platformEvents.filter((e) => e.type === 'ZONE_CHANGE');
  const outageEvents = platformEvents.filter((e) => e.type === 'APP_OUTAGE' && e.localDate === current.date);
  if (incentiveDropped && incentiveEvents.length) {
    const e = incentiveEvents[incentiveEvents.length - 1];
    inferences.push({
      text: `The ${dates.short(e.localDate)} notice "${e.title}" may be related: it came shortly before this shift, and it concerns the same bonus.`,
      confidence: 'MEDIUM',
      basis: `Timing and subject of platform event ${dates.short(e.localDate)}`
    });
  }
  if (incentiveDropped && zoneEvents.length && otherZoneOrders > 0) {
    const e = zoneEvents[zoneEvents.length - 1];
    inferences.push({
      text: `The ${dates.short(e.localDate)} zone-map revision may be relevant, because ${otherZoneOrders} orders on this shift were outside ${current.zone}.`,
      confidence: 'LOW',
      basis: 'Timing of the zone notice and the zone mix of this shift'
    });
  }
  if (outageEvents.length && primary === 'order_volume') {
    inferences.push({
      text: `The platform disruption recorded for this evening (${outageEvents[0].title}) likely reduced order volume.`,
      confidence: 'MEDIUM',
      basis: 'Platform event on the same evening'
    });
  }

  // ── MEMORY (Hindsight) ─────────────────────────────────────────────────────
  const memories = useMemory ? (memory?.memories || []) : [];
  let previousOutcomeUsed = null;
  for (const m of memories) {
    // The anomaly memory for this very shift is the current event, not history.
    if (m.category === 'historical_anomaly' && m.localDate === current.date) continue;
    const linked = linkedCase(m, previousCases);
    historicalContext.push({
      memoryId: m.id,
      text: m.text,
      category: m.category,
      localDate: m.localDate,
      whyRecalled: m.whyRecalled || 'Relevant to the question',
      linkedCase: linked ? { id: linked.id, caseNumber: linked.caseNumber } : null
    });
    const incentiveRootCause = m.metadata?.rootCause ? /INCENTIVE/.test(m.metadata.rootCause) : incentiveTerms.test(m.text);
    if (!previousOutcomeUsed && m.category === 'investigation_outcome' && incentiveRootCause) {
      previousOutcomeUsed = { memory: m, linked };
    }
  }

  const isIncentiveAnomaly = (m) => (m.metadata?.primaryFactor
    ? m.metadata.primaryFactor === 'incentive'
    : incentiveTerms.test(m.text) && !/consistent with lower order volume/i.test(m.text));
  const priorAnomalies = memories
    .filter((m) => m.category === 'historical_anomaly' && m.localDate && m.localDate < current.date && isIncentiveAnomaly(m))
    .sort((a, b) => (b.localDate < a.localDate ? -1 : 1));
  if (incentiveDropped && priorAnomalies.length) {
    const m = priorAnomalies[0];
    const days = dates.diffDays(current.date, m.localDate);
    inferences.push({
      text: `This has happened before: I remember a similar incentive-related drop ${days} days earlier (${dates.short(m.localDate)}).`,
      confidence: 'HIGH',
      basis: 'Recalled from Hindsight memory',
      evidence: [key.memory(m.id)]
    });
  }

  if (incentiveDropped && previousOutcomeUsed) {
    const { memory: m, linked } = previousOutcomeUsed;
    inferences.push({
      text: `A previous investigation${linked ? ` (${linked.caseNumber})` : ''} with the same pattern — lower earnings with normal order volume — was traced to an incentive eligibility condition. Based on that experience, incentive eligibility should be checked before assuming lower demand.`,
      confidence: 'MEDIUM',
      basis: 'Previous investigation outcome recalled from Hindsight',
      evidence: [key.memory(m.id), ...(linked ? [key.investigation(linked.id)] : [])]
    });
    if (linked && linked.sessionAcceptanceRate !== null && current.acceptanceRate > linked.sessionAcceptanceRate + 3) {
      inferences.push({
        text: `However, the condition from last time may not be the same one: your acceptance rate this time was ${current.acceptanceRate}%, compared with ${linked.sessionAcceptanceRate}% in ${linked.caseNumber}. A different eligibility condition may be involved.`,
        confidence: 'MEDIUM',
        basis: `Structured comparison with the session behind ${linked.caseNumber}`,
        evidence: [key.session(current.sessionId), key.investigation(linked.id)]
      });
    }
    actions.push({ text: `Check ${current.incentiveProgram || 'incentive'} eligibility first — that is what resolved your previous case${linked ? ` ${linked.caseNumber}` : ''}.`, priority: 1, fromMemory: true });
  }

  // ── UNKNOWNS ───────────────────────────────────────────────────────────────
  if (incentiveDropped) {
    unknowns.push({ text: `The available records do not show why this shift was marked not eligible for the ${current.incentiveProgram || 'incentive'}.` });
  }
  for (const e of [...incentiveEvents, ...zoneEvents]) {
    if (/does not (state|say)/i.test(e.description)) {
      unknowns.push({ text: `The ${dates.short(e.localDate)} notice does not say exactly what changed ("${e.title}").` });
    }
  }
  if (incentiveDropped && otherZoneOrders > 0) {
    unknowns.push({ text: `Whether orders delivered outside ${current.zone} count toward bonus eligibility.` });
  }
  if (useMemory && memory && ['UNAVAILABLE', 'FAILED'].includes(memory.status)) {
    unknowns.push({ text: 'Historical agent memory was unavailable, so previous cases and learned patterns were not considered.' });
  }

  // ── ACTIONS / QUESTIONS ────────────────────────────────────────────────────
  if (incentiveDropped) {
    questions.push(`Which ${current.incentiveProgram || 'incentive'} eligibility condition was not met on ${dateLabel}?`);
    questions.push(`What are the current eligibility criteria for the ${current.incentiveProgram || 'incentive'}, and from what date do they apply?`);
    if (otherZoneOrders > 0 && zoneEvents.length) questions.push(`After the ${dates.short(zoneEvents[zoneEvents.length - 1].localDate)} zone revision, do deliveries in ${otherZones.map(([z]) => z).join(', ')} count toward eligibility?`);
    actions.push({ text: `Request the ${current.incentiveProgram || 'incentive'} eligibility record for ${dateLabel} from platform support.`, priority: 2 });
  }
  if (primary === 'deductions') {
    questions.push(`Can the platform provide an itemised deduction breakdown for ${dateLabel}?`);
    actions.push({ text: 'Request an itemised deduction statement.', priority: 2 });
  }
  if (primary === 'pay_per_order') {
    questions.push('Has the per-order pay rate changed for this zone or time window?');
  }
  if (evaluation && ['SIGNIFICANT_CHANGE', 'INVESTIGATION_RECOMMENDED'].includes(evaluation.severity) && primary !== 'order_volume') {
    actions.push({ text: 'Open an investigation to preserve this evidence and generate a report.', priority: 3 });
  }
  if (primary === 'order_volume') {
    actions.push({ text: 'No platform clarification appears necessary: the change is consistent with lower order volume.', priority: 3 });
  }

  const prefersTimeline = memories.some((m) => m.category === 'worker_preference' && /timeline|chronolog/i.test(m.text));

  let summary;
  if (!enoughHistory) {
    summary = `On ${dateLabel} you earned ${inr(current.net)} from ${current.orders} orders. There is not yet enough comparable history to judge whether that is unusual.`;
  } else if (evaluation.deviationPct < -10) {
    summary = `Your earnings on ${dateLabel} were ${pct(evaluation.deviationPct)} below your personal ${current.dayName}-${current.timeWindow} baseline (${inr(current.net)} vs ${inr(baseline.net.median)}).`;
    if (primary === 'incentive') summary += ` Your order volume was normal; the main difference is the ${current.incentiveProgram || 'incentive'} (${inr(current.incentive)} instead of ${inr(baseline.incentive.median)}).`;
    else if (primary === 'order_volume') summary += ` You completed fewer orders than usual (${current.orders} vs ${baseline.orders.min}–${baseline.orders.max}), which explains most of the difference.`;
    if (incentiveDropped && priorAnomalies.length) summary += ` I found a similar situation in your history ${dates.diffDays(current.date, priorAnomalies[0].localDate)} days ago.`;
    if (incentiveDropped && previousOutcomeUsed) summary += ` The previous investigation${previousOutcomeUsed.linked ? ` (${previousOutcomeUsed.linked.caseNumber})` : ''} was resolved after the incentive eligibility condition was clarified, so I recommend checking the current eligibility record first.`;
  } else {
    summary = `Your earnings on ${dateLabel} (${inr(current.net)}) are within ${pct(evaluation.deviationPct)} of your personal baseline (${inr(baseline.net.median)}).`;
  }

  return finalize({ current, facts, inferences, unknowns, historicalContext, actions, questions, evaluation, summary, prefersTimeline, analysis, previousOutcomeUsed });
};

const finalize = ({ current, facts, inferences, unknowns, historicalContext, actions, questions, evaluation, summary, prefersTimeline = false, analysis = null, previousOutcomeUsed = null }) => ({
  summary,
  facts,
  inferences,
  unknowns,
  historicalContext,
  recommendedActions: actions.sort((a, b) => a.priority - b.priority),
  recommendedQuestions: questions,
  severity: evaluation?.severity || null,
  deviationPct: evaluation?.deviationPct ?? null,
  primaryFactor: evaluation?.decomposition?.primaryFactor || null,
  prefersTimeline,
  usedPreviousOutcome: Boolean(previousOutcomeUsed),
  timeline: analysis ? buildTimeline(analysis, historicalContext) : [],
  sessionId: current.sessionId,
  date: current.date
});

/** Chronological evidence timeline (comparables → events → current → memory). */
const buildTimeline = (analysis, historicalContext) => {
  const { current, comparables, platformEvents } = analysis;
  const rows = [
    ...comparables.map((c) => ({
      date: c.date, kind: 'comparable', title: `${inr(c.net)} · ${c.orders} orders`,
      detail: `${c.dayName} ${c.window} · ${c.incentiveProgram ? `${c.incentiveProgram} ${inr(c.incentive)}` : 'no incentive programme'}`,
      evidenceId: key.comparable(c.sessionId), status: c.incentive > 0 || !c.incentiveProgram ? 'normal' : 'attention'
    })),
    ...platformEvents.map((e) => ({ date: e.localDate, kind: 'platform_event', title: e.title, detail: e.description, evidenceId: key.event(e.id), status: 'event' })),
    {
      date: current.date, kind: 'current', title: `${inr(current.net)} · ${current.orders} orders`,
      detail: `${current.dayName} ${current.window} · ${current.incentiveProgram ? `${current.incentiveProgram} ${inr(current.incentive)}${current.incentiveNote ? ` ("${current.incentiveNote}")` : ''}` : ''}`,
      evidenceId: key.session(current.sessionId), status: 'attention'
    },
    ...historicalContext.filter((h) => h.localDate && ['historical_anomaly', 'investigation_outcome'].includes(h.category)).map((h) => ({
      date: h.localDate, kind: 'memory', title: h.category === 'investigation_outcome' ? 'Previous investigation outcome (memory)' : 'Previous anomaly (memory)',
      detail: h.text, evidenceId: key.memory(h.memoryId), status: 'memory'
    }))
  ];
  return rows.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));
};

module.exports = { reasonAboutSession, buildEvidence, buildTimeline, evidenceKey: key };
